In [2]:
import pandas as pd

In [41]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_a.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_a=pd.concat(data_frame,ignore_index=True)

In [42]:

bigbasket_a.columns

Index(['Unnamed: 0', 'name', 'Category', 'mrp', 'selling_price',
       'offer_percentage', 'delivery_time', 'quantity', 'scrape_date',
       'scrape_time', 'location', 'Delivery_Charges(Handelling+Delivery)',
       'Period', 'Surge', 'Climate', 'Surge_charges', 'Late_Night_Charges',
       'Delivery_Charges(Handelling+Delivery+Late_Night_Charge)'],
      dtype='object')

In [43]:
bigbasket_a

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,11 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,12:32:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,11 MINS,500 g,2026-03-06,12:32:39,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
317,37,fresho! Lemon,Vegetable,33.0,10.0,70% OFF,11 MINS,150 g,2026-03-06,12:32:51,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,11 MINS,100 g,2026-03-06,12:33:02,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
319,39,fresho! Bottle Gourd,Vegetable,34.0,27.2,20% OFF,11 MINS,1 pc - (300 g - 450 g approx.),2026-03-06,12:33:14,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0

In [44]:
bigbasket_a[["mrp","Period","Delivery_Charges(Handelling+Delivery)"]].head(10)

            mrp Period  Delivery_Charges(Handelling+Delivery)
0  Out of Stock  Night                                    0.0
1           150  Night                                   26.0
2            32  Night                                   26.0
3            42  Night                                   26.0
4            42  Night                                   26.0
5  Out of Stock  Night                                    0.0
6            44  Night                                   26.0
7            63  Night                                   26.0
8            80  Night                                   26.0
9  Out of Stock  Night                                    0.0

In [45]:
bigbasket_a[bigbasket_a["mrp"]!="Out of stock"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,11 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,12:32:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,11 MINS,500 g,2026-03-06,12:32:39,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
317,37,fresho! Lemon,Vegetable,33.0,10.0,70% OFF,11 MINS,150 g,2026-03-06,12:32:51,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,11 MINS,100 g,2026-03-06,12:33:02,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
319,39,fresho! Bottle Gourd,Vegetable,34.0,27.2,20% OFF,11 MINS,1 pc - (300 g - 450 g approx.),2026-03-06,12:33:14,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0

In [32]:
bigbasket_a[bigbasket_a["Period"]=="Night"].head(20)

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
5,5,Amul Taaza Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:35:28,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
6,6,Sids Farm Cow Milk,Milk,44,44,NaN,20 MINS,500 ml,03-03-2026,23:35:39,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
7,7,Sids Farm Buffalo A2 Milk,Milk,63,60,5% OFF,19 MINS,500 ml,03-03-2026,23:35:50,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
8,8,Amul Gold Homogenised Standardised,Milk,80,80,NaN,20 MINS,1 L,03-03-2026,23:36:01,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
9,9,Amul Buffalo Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:36:11,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
10,10,Amul Taaza Homogenised Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:36:22,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
11,11,Amul Fresh Malai Paneer,Paneer,94,94,NaN,19 MINS,200 g - Pouch,03-03-2026,23:36:33,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
12,12,Super Cool Frozen Skinless Chicken Curry Cut,Chicken,160,160,NaN,21 MINS,450 g - Tray Pack,03-03-2026,23:36:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
13,13,fresho! Chicken Breast Boneless,Chicken,324,210,35% OFF,22 MINS,500 g - (2-4 pcs),03-03-2026,23:36:53,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
14,14,Super Cool Frozen Skinless Chicken Drumsticks,Chicken,185,185,NaN,17 MINS,450 g - Tray Pack,03-03-2026,23:37:04,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
15,15,"fresho! Red Onion Skinned - Peeled, Small",Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:37:14,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
16,16,fresho! Onion - Organically Grown,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:37:24,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
17,17,"fresho! Tomato - Local, Organically Grown",Vegetable,48,34.5,28% OFF,18 MINS,1 kg,03-03-2026,23:37:34,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
18,18,"fresho! Tomato - Hybrid, Organically Grown",Vegetable,31,24.8,20% OFF,16 MINS,500 g,03-03-2026,23:37:45,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
19,19,fresho! Hybrid Tomato,Vegetable,52,41.6,20% OFF,21 MINS,1 kg,03-03-2026,23:37:55,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN

In [61]:
# bigbasket_a["Delivery_Charges(Handelling+Delivery)"]=bigbasket_a["Delivery_Charges(Handelling+Delivery)"]+bigbasket_a["Late_Night_Charges"]

In [114]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [115]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=37.0

In [116]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [117]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=26.0

In [58]:
bigbasket_a[bigbasket_a["Period"]=="Afternoon"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
280,0,Heritage Fresh Paneer,Paneer,115.0,101.0,12% OFF,11 MINS,200 g - Pouch,2026-03-06,12:26:20,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
281,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,12:26:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,0.0
282,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,11 MINS,500 ml - Pouch,2026-03-06,12:26:39,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
283,3,Heritage Full Cream Milk,Milk,32.0,31.0,3% OFF,11 MINS,500 ml - Pouch,2026-03-06,12:26:49,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
284,4,Arokya Full Cream Milk,Milk,42.0,40.0,5% OFF,11 MINS,500 ml,2026-03-06,12:27:00,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
285,5,Amul Taaza Toned Milk,Milk,16,16,3% OFF,11 MINS,200 ml - Carton,2026-03-06,12:27:10,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
286,6,Sids Farm Cow Milk,Milk,44,44,NaN,11 MINS,500 ml,2026-03-06,12:27:21,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
287,7,Sids Farm Buffalo A2 Milk,Milk,266,266,NaN,11 MINS,200 g,2026-03-06,12:27:31,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
288,8,Amul Gold Homogenised Standardised,Milk,80,80,NaN,11 MINS,1 L,2026-03-06,12:27:41,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
289,9,Amul Buffalo Milk,Milk,40,40,NaN,11 MINS,500 ml - Pouch,2026-03-06,12:27:51,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
290,10,Amul Taaza Homogenised Toned Milk,Milk,16,16,3% OFF,11 MINS,200 ml - Carton,2026-03-06,12:28:01,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
291,11,Amul Fresh Malai Paneer,Paneer,94,94,NaN,11 MINS,200 g - Pouch,2026-03-06,12:28:10,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
292,12,Super Cool Frozen Skinless Chicken Curry Cut,Chicken,160,160,NaN,11 MINS,450 g - Tray Pack,2026-03-06,12:28:20,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
293,13,fresho! Chicken Breast Boneless,Chicken,584.0,449.0,23% OFF,11 MINS,1 kg - (4-6 pcs),2026-03-06,12:28:30,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
294,14,Super Cool Frozen Skinless Chicken Drumsticks,Chicken,185,185,NaN,11 MINS,450 g - Tray Pack,2026-03-06,12:28:40,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
295,15,"fresho! Red Onion Skinned - Peeled, Small",Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,12:28:49,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,0.0
296,16,fresho! Onion - Organically Grown,Vegetable,51.0,31.0,39% OFF,11 MINS,1 kg,2026-03-06,12:29:00,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
297,17,"fresho! Tomato - Local, Organically Grown",Vegetable,42.0,33.6,20% OFF,11 MINS,1 kg,2026-03-06,12:29:11,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
298,18,"fresho! Tomato - Hybrid, Organically Grown",Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,12:29:22,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,0.0
299,19,fresho! Hybrid Tomato,Vegetable,27.0,21.6,20% OFF,11 MINS,500 g,2026-03-06,12:29:33,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
300,20,FreshtoHome Premium Tender Goat Curry Cut,Meat,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,12:29:43,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,0.0
301,21,fresho! Goat Meat Curry Cut,Meat,600.0,509.0,15% OFF,11 MINS,500 g,2026-03-06,12:29:54,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
302,22,fresho! Potato,Vegetable,41.0,25.0,39% OFF,11 MINS,1 kg,2026-03-06,12:30:06,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
303,23,fresho! Potato - Organically Grown,Vegetable,53.0,32.5,39% OFF,11 MINS,1 kg,2026-03-06,12:30:17,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
304,24,fresho! Carrot,Vegetable,19.0,5.0,74% OFF,11 MINS,250 g,2026-03-06,12:30:28,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
305,25,fresho! Beetroot,Vegetable,32.0,25.6,20% OFF,11 MINS,500 g,2026-03-06,12:30:40,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
306,26,fresho! Cucumber,Vegetable,31.0,20.0,35% OFF,11 MINS,500 g,2026-03-06,12:30:51,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
307,27,fresho! English Cucumber,Vegetable,43.0,34.4,20% OFF,11 MINS,500 g,2026-03-06,12:31:02,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
308,28,"fresho! Farm Eggs, Regular",Eggs,90.0,47.0,48% OFF,11 MINS,6 pcs,2026-03-06,12:31:13,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
309,29,fresho! Premium Large White Eggs - Protein & V...,Eggs,200.0,105.0,48% OFF,11 MINS,12 pcs,2026-03-06,12:31:24,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
310,30,"Farm Eggs-Medium, Brown",Eggs,115.0,69.0,40% OFF,11 MINS,6 pcs,2026-03-06,12:31:35,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
311,31,"fresho! Apple - Red Delicious, Premium",Fruit,404.0,323.2,20% OFF,11 MINS,4 pcs - (Approx. 600 g -700 g),2026-03-06,12:31:46,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
312,32,fresho! Baby Apple Shimla,Fruit,294.0,229.0,22% OFF,11 MINS,1 kg,2026-03-06,12:31:56,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
313,33,fresho! Apple - Green,Fruit,176.0,154.88,12% OFF,11 MINS,2 pcs - Approx. 260 g - 300 g,2026-03-06,12:32:07,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
314,34,fresho! Banana - Raw Green,Fruit,24.0,21.12,12% OFF,11 MINS,NaN,2026-03-06,12:32:18,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,11 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,12:32:29,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,11 MINS,500 g,2026-03-06,12:32:39,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
317,37,fresho! Lemon,Vegetable,33.0,10.0,70% OFF,11 MINS,150 g,2026-03-06,12:32:51,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,11 MINS,100 g,2026-03-06,12:33:02,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
319,39,fresho! Bottle Gourd,Vegetable,34.0,27.2,20% OFF,11 MINS,1 pc - (300 g - 450 g approx.),2026-03-06,12:33:14,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0

In [73]:
bigbasket_a["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [69]:
bigbasket_a["Delivery_Charges(Handelling+Delivery)"]

0       0.0
1      26.0
2      26.0
3      26.0
4      26.0
       ...
315    21.0
316    21.0
317    21.0
318    21.0
319    21.0
Name: Delivery_Charges(Handelling+Delivery), Length: 320, dtype: float64

In [81]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_su.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_su=(pd.concat(data_frame,ignore_index=True))

In [153]:
bigbasket_su[bigbasket_su["Period"]=="Night"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([32., nan])

In [143]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [149]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [145]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [146]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=35.0

In [155]:
bigbasket_s["Delivery_Charges(Handelling+Delivery)"].fillna(0,inplace=True)

C:\Users\veera\AppData\Local\Temp\ipykernel_42572\2310741765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bigbasket_s["Delivery_Charges(Handelling+Delivery)"].fillna(0,inplace=True)

In [157]:
bigbasket_s["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [50]:
bigbasket_su=bigbasket_su.drop(columns="Unnamed: 0")

In [137]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_s.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_s=(pd.concat(data_frame,ignore_index=True))

In [138]:
bigbasket_s

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charges)
0,0,Heritage Fresh Paneer,Paneer,115,101,12% OFF,11 MINS,200 g - Pouch,03-03-2026,23:20:38,Beeramguda,21.0,Night,NaN,Clear,No,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:20:48,Beeramguda,0.0,Night,NaN,Clear,No,NaN
2,2,Heritage Daily Health Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:20:58,Beeramguda,0.0,Night,NaN,Clear,No,NaN
3,3,Heritage Full Cream Milk,Milk,32,31,3% OFF,11 MINS,500 ml - Pouch,03-03-2026,23:21:08,Beeramguda,21.0,Night,NaN,Clear,No,NaN
4,4,Arokya Full Cream Milk,Milk,36,36,NaN,11 MINS,500 ml - Pouch,03-03-2026,23:21:19,Beeramguda,21.0,Night,NaN,Clear,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129,79,39% OFF,8 MINS,1 kg - (Approx. 6 - 8 pcs),06-03-2026,09:09:26,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
316,36,fresho! Mini Orange Imported,Fruit,144,115.2,20% OFF,8 MINS,500 g,06-03-2026,09:09:36,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
317,37,fresho! Lemon,Vegetable,54,38.5,29% OFF,8 MINS,250 g,06-03-2026,09:09:47,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17,11,35% OFF,8 MINS,100 g,06-03-2026,09:09:57,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
319,39,fresho! Bottle Gourd,Vegetable,34,27.2,20% OFF,8 MINS,1 pc - (300 g - 450 g approx.),06-03-2026,09:10:07,Beeramguda,NaN,Morning,NaN,Clear,No,21.0

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
blinkit_s[(blinkit_s["mrp"]!="Out of Stock")& (blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna())]=27

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=32.0

In [142]:
bigbasket_s[bigbasket_s["Period"]=="Evening"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([nan])

In [158]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,10):
    file=f"{path}blinkit_{i}_a.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_a=(pd.concat(data_frame,ignore_index=True))

In [159]:
blinkit_a

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,13 MINS,200 g,2026-03-03,12:56:15,KPHB colony,36,Afternoon,NaN,sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,13 MINS,240 g,2026-03-03,12:56:29,KPHB colony,36,Afternoon,NaN,sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,13 MINS,500 ml,2026-03-03,12:56:44,KPHB colony,36,Afternoon,NaN,sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:56:59,KPHB colony,36,Afternoon,NaN,sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:57:15,KPHB colony,36,Afternoon,NaN,sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,35,Nagpur - Orange,Fruit,76.0,60,21% OFF,13 MINS,500 g,2026-03-04,23:29:19,KPHB colony,36,Night,NaN,clear,No
356,36,Mini Orange (Imported),Fruit,65.0,57,12% OFF,13 MINS,200 g,2026-03-04,23:29:32,KPHB colony,36,Night,NaN,clear,No
357,37,Lemon (Nimakaya),Vegetable,45.0,36,20% OFF,13 MINS,200 g,2026-03-04,23:29:46,KPHB colony,36,Night,NaN,clear,No
358,38,Green Chilli (Mirapakaya),Vegetable,12.0,11,8% OFF,14 MINS,100 g,2026-03-04,23:29:59,KPHB colony,36,Night,NaN,clear,No
359,39,Bottle Gourd (Sorakaya),Vegetable,31.0,25,19% OFF,14 MINS,400 g,2026-03-04,23:30:12,KPHB colony,36,Night,NaN,clear,No

In [162]:
blinkit_a[blinkit_a["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([36, 35])

In [170]:
blinkit_a[blinkit_a["Delivery_Charges(Handelling+Delivery)"]==36]["Period"].unique()

array(['Afternoon', 'Evening', 'Night', 'Morning'], dtype=object)

In [171]:
blinkit_a["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [172]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,11):
    file=f"{path}blinkit_{i}_su.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_su=(pd.concat(data_frame,ignore_index=True))

In [173]:
blinkit_su

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,8 MINS,200 g,2026-03-03,11:53:05,Madhapur,36,Afternoon,NaN,Sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,8 MINS,240 g,2026-03-03,11:53:19,Madhapur,36,Afternoon,NaN,Sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,8 MINS,500 ml,2026-03-03,11:53:33,Madhapur,36,Afternoon,NaN,Sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,8 MINS,500 ml,2026-03-03,11:53:50,Madhapur,36,Afternoon,NaN,Sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,8 MINS,500 ml,2026-03-03,11:54:03,Madhapur,36,Afternoon,NaN,Sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,35,Nagpur - Orange,Fruit,71.0,60,NaN,8 MINS,500 g,2026-03-05,21:15:16,Madhapur,35,Night,NaN,Clear,No
396,36,Mini Orange (Imported),Fruit,77.0,67,12% OFF,8 MINS,200 g,2026-03-05,21:15:28,Madhapur,35,Night,NaN,Clear,No
397,37,Lemon (Nimakaya),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-05,21:15:40,Madhapur,0,Night,NaN,Clear,No
398,38,Green Chilli (Mirapakaya),Vegetable,22.0,18,18% OFF,8 MINS,100 g,2026-03-05,21:15:53,Madhapur,35,Night,NaN,Clear,No
399,39,Bottle Gourd (Sorakaya),Vegetable,68.0,55,NaN,8 MINS,400 g,2026-03-05,21:16:05,Madhapur,35,Night,NaN,Clear,No

In [174]:
blinkit_su["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [200]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,11):
    file=f"{path}blinkit_{i}_s.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_s=(pd.concat(data_frame,ignore_index=True))

In [201]:
blinkit_s[blinkit_s["Period"]=="Night"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
80,0,Heritage Fresh Paneer,Paneer,115,101,12% OFF,7 MINS,200 g,03-03-2026,22:28:29,Beeramguda,27.0,Night,NaN,Clear,No
81,1,Heritage Nourish+ High Protein Paneer,Paneer,150,125,16% OFF,7 MINS,240 g,03-03-2026,22:28:42,Beeramguda,27.0,Night,NaN,Clear,No
82,2,Heritage Daily Health Toned Milk,Milk,33,31,6% OFF,7 MINS,450 ml,03-03-2026,22:28:54,Beeramguda,27.0,Night,NaN,Clear,No
83,3,Heritage Full Cream Milk,Milk,42,42,NaN,7 MINS,500 ml,03-03-2026,22:29:06,Beeramguda,27.0,Night,NaN,Clear,No
84,4,Arokya Full Cream Milk,Milk,42,42,NaN,7 MINS,500 ml,03-03-2026,22:29:18,Beeramguda,27.0,Night,NaN,Clear,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,35,Nagpur - Orange,Fruit,70.0,60,14% OFF,14 MINS,500 g,2026-03-05,22:03:27,Beeramguda,27.0,Night,NaN,Clear,No
356,36,Mini Orange (Imported),Fruit,112.0,98,12% OFF,14 MINS,200 g,2026-03-05,22:03:44,Beeramguda,27.0,Night,NaN,Clear,No
357,37,Lemon (Nimakaya),Vegetable,43.0,36,16% OFF,14 MINS,200 g,2026-03-05,22:03:59,Beeramguda,27.0,Night,NaN,Clear,No
358,38,Green Chilli (Mirapakaya),Vegetable,13.0,11,15% OFF,14 MINS,100 g,2026-03-05,22:04:17,Beeramguda,27.0,Night,NaN,Clear,No
359,39,Bottle Gourd (Sorakaya),Vegetable,32.0,25,NaN,13 MINS,400 g,2026-03-05,22:04:34,Beeramguda,27.0,Night,NaN,Clear,No

In [180]:
blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(40)

In [202]:
blinkit_s[blinkit_s["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([27., 29., 25., 21., nan])

In [203]:
blinkit_s[blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
240,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,12 MINS,200 g,2026-03-04,23:12:10,Beeramguda,NaN,NaN,NaN,NaN,NaN
241,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,12 MINS,240 g,2026-03-04,23:12:23,Beeramguda,NaN,NaN,NaN,NaN,NaN
242,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,10 MINS,500 ml,2026-03-04,23:12:35,Beeramguda,NaN,NaN,NaN,NaN,NaN
243,3,Heritage Full Cream Milk,Milk,42,42,NaN,10 MINS,500 ml,2026-03-04,23:12:47,Beeramguda,NaN,NaN,NaN,NaN,NaN
244,4,Arokya Full Cream Milk,Milk,42,42,NaN,11 MINS,500 ml,2026-03-04,23:13:00,Beeramguda,NaN,NaN,NaN,NaN,NaN
245,5,Sids Farm Buffalo A2 Milk,Milk,63,63,NaN,11 MINS,500 ml,2026-03-04,23:13:12,Beeramguda,NaN,NaN,NaN,NaN,NaN
246,6,Amul Taaza Toned Milk,Milk,16,16,NaN,11 MINS,200 ml,2026-03-04,23:13:24,Beeramguda,NaN,NaN,NaN,NaN,NaN
247,7,Sids Farm Cow Milk,Milk,44,44,NaN,11 MINS,500 ml,2026-03-04,23:13:37,Beeramguda,NaN,NaN,NaN,NaN,NaN
248,8,Amul Gold Homogenised Standardised,Other,80,80,NaN,11 MINS,1 ltr,2026-03-04,23:13:49,Beeramguda,NaN,NaN,NaN,NaN,NaN
249,9,Amul Buffalo Milk,Milk,59.0,51,13% OFF,11 MINS,450 ml,2026-03-04,23:14:01,Beeramguda,NaN,NaN,NaN,NaN,NaN
250,10,Amul Taaza Homogenised Toned Milk,Milk,75,75,NaN,11 MINS,1 ltr,2026-03-04,23:14:13,Beeramguda,NaN,NaN,NaN,NaN,NaN
251,11,Amul Fresh Malai Paneer,Paneer,94,94,NaN,11 MINS,200 g,2026-03-04,23:14:26,Beeramguda,NaN,NaN,NaN,NaN,NaN
252,12,FreshtoHome Chicken - Skinless Curry Cut,Chicken,169.0,129,23% OFF,11 MINS,500 g,2026-03-04,23:14:38,Beeramguda,NaN,NaN,NaN,NaN,NaN
253,13,Sneha Select Boneless Chicken Breast,Chicken,260,260,NaN,11 MINS,500 g,2026-03-04,23:14:50,Beeramguda,NaN,NaN,NaN,NaN,NaN
254,14,Super Cool Frozen Skinless Chicken Drumstickso...,Chicken,185,185,NaN,13 MINS,450 g,2026-03-04,23:15:02,Beeramguda,NaN,NaN,NaN,NaN,NaN
255,15,Organically Grown Onion (Ulligadda),Vegetable,45.0,39,13% OFF,13 MINS,250 g,2026-03-04,23:15:14,Beeramguda,NaN,NaN,NaN,NaN,NaN
256,16,Organically Grown Tomato (Desi),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:15:25,Beeramguda,NaN,NaN,NaN,NaN,NaN
257,17,Desi Tomato (Tamatar),Vegetable,25.0,17,NaN,12 MINS,500 g,2026-03-04,23:15:37,Beeramguda,NaN,NaN,NaN,NaN,NaN
258,18,Hybrid Tomato (Tamatar),Vegetable,28.0,18,NaN,12 MINS,500 g,2026-03-04,23:15:49,Beeramguda,NaN,NaN,NaN,NaN,NaN
259,19,FreshToHome Mutton Curry Cut,Meat,585,585,NaN,11 MINS,500 g,2026-03-04,23:16:00,Beeramguda,NaN,NaN,NaN,NaN,NaN
260,20,Premier Mutton Curry Cut,Meat,585,585,NaN,11 MINS,500 g,2026-03-04,23:16:12,Beeramguda,NaN,NaN,NaN,NaN,NaN
261,21,Potato (Bangala Dumpa),Vegetable,24.0,21,12% OFF,11 MINS,500 g,2026-03-04,23:16:24,Beeramguda,NaN,NaN,NaN,NaN,NaN
262,22,Oraganically Grown Potato,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:16:35,Beeramguda,NaN,NaN,NaN,NaN,NaN
263,23,Orange Carrot,Vegetable,22.0,19,13% OFF,11 MINS,500 g,2026-03-04,23:16:47,Beeramguda,NaN,NaN,NaN,NaN,NaN
264,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:17:00,Beeramguda,NaN,NaN,NaN,NaN,NaN
265,25,Green Cucumber (Kheera),Vegetable,30.0,24,20% OFF,12 MINS,500 g,2026-03-04,23:17:12,Beeramguda,NaN,NaN,NaN,NaN,NaN
266,26,English Cucumber,Vegetable,27.0,23,14% OFF,14 MINS,500 g,2026-03-04,23:17:24,Beeramguda,NaN,NaN,NaN,NaN,NaN
267,27,Sneha Select Table White Eggs,Eggs,70.0,42,40% OFF,14 MINS,6 pcs,2026-03-04,23:17:36,Beeramguda,NaN,NaN,NaN,NaN,NaN
268,28,Hello Eggs Brown Eggs,Eggs,75.0,64,14% OFF,14 MINS,6 pcs,2026-03-04,23:17:48,Beeramguda,NaN,NaN,NaN,NaN,NaN
269,29,Licious White Protein Rich Egg,Eggs,85,85,NaN,14 MINS,6 pcs,2026-03-04,23:18:01,Beeramguda,NaN,NaN,NaN,NaN,NaN
270,30,Shimla Apple,Fruit,143.0,110,23% OFF,14 MINS,500 g,2026-03-04,23:18:13,Beeramguda,NaN,NaN,NaN,NaN,NaN
271,31,Red Delicious Apple - Imported,Fruit,180.0,148,17% OFF,15 MINS,225 g,2026-03-04,23:18:24,Beeramguda,NaN,NaN,NaN,NaN,NaN
272,32,Granny Smith Apple,Fruit,207.0,165,20% OFF,15 MINS,300 g,2026-03-04,23:18:36,Beeramguda,NaN,NaN,NaN,NaN,NaN
273,33,Banana (Aratipandu),Fruit,71.0,56,21% OFF,15 MINS,500 g,2026-03-04,23:18:49,Beeramguda,NaN,NaN,NaN,NaN,NaN
274,34,Raw Banana (Aratipandu),Fruit,36.0,31,NaN,14 MINS,3 pcs,2026-03-04,23:19:01,Beeramguda,NaN,NaN,NaN,NaN,NaN
275,35,Nagpur - Orange,Fruit,72.0,60,16% OFF,14 MINS,500 g,2026-03-04,23:19:14,Beeramguda,NaN,NaN,NaN,NaN,NaN
276,36,Mini Orange (Imported),Fruit,74.0,57,22% OFF,16 MINS,200 g,2026-03-04,23:19:26,Beeramguda,NaN,NaN,NaN,NaN,NaN
277,37,Lemon (Nimakaya),Vegetable,46.0,36,21% OFF,16 MINS,200 g,2026-03-04,23:19:38,Beeramguda,NaN,NaN,NaN,NaN,NaN
278,38,Green Chilli (Mirapakaya),Vegetable,15.0,12,20% OFF,16 MINS,100 g,2026-03-04,23:19:50,Beeramguda,NaN,NaN,NaN,NaN,NaN
279,39,Bottle Gourd (Sorakaya),Vegetable,31.0,25,19% OFF,13 MINS,400 g,2026-03-04,23:20:02,Beeramguda,NaN,NaN,NaN,NaN,NaN

In [205]:
blinkit_s.loc[(blinkit_s["mrp"]!="Out of Stock")& (blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()),"Delivery_Charges(Handelling+Delivery)"]=27

In [206]:
blinkit_s[blinkit_s["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([27., 29., 25., 21.])

In [207]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:44:59,Beeramguda,0.0,Afternoon,NaN,Sunny,No
7,7,Sids Farm Cow Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:46:26,Beeramguda,0.0,Afternoon,NaN,Sunny,No
12,12,FreshtoHome Chicken - Skinless Curry Cut,Chicken,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:47:27,Beeramguda,0.0,Afternoon,NaN,Sunny,No
14,14,Super Cool Frozen Skinless Chicken Drumstickso...,Chicken,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:47:52,Beeramguda,0.0,Afternoon,NaN,Sunny,No
15,15,Organically Grown Onion (Ulligadda),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:04,Beeramguda,0.0,Afternoon,NaN,Sunny,No
17,17,Desi Tomato (Tamatar),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:31,Beeramguda,0.0,Afternoon,NaN,Sunny,No
18,18,Hybrid Tomato (Tamatar),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:44,Beeramguda,0.0,Afternoon,NaN,Sunny,No
20,20,Premier Mutton Curry Cut,Meat,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:08,Beeramguda,0.0,Afternoon,NaN,Sunny,No
21,21,Potato-(Bangala Dumpa),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:21,Beeramguda,0.0,Afternoon,NaN,Sunny,No
22,22,Oraganically Grown Potato,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:33,Beeramguda,0.0,Afternoon,NaN,Sunny,No
24,24,Oragincally Grown Carrot,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:50:00,Beeramguda,0.0,Afternoon,NaN,Sunny,No
25,25,Green Cucumber (Kheera),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:50:13,Beeramguda,0.0,Afternoon,NaN,Sunny,No
26,26,"Organically Grown Green Cucumber (Khira, Kheera)",Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:50:27,Beeramguda,0.0,Afternoon,NaN,Sunny,No
34,34,Raw Banana (Aratipandu),Fruit,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:52:14,Beeramguda,0.0,Afternoon,NaN,Sunny,No
64,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,19:46:07,Beeramguda,0.0,Evening,NaN,Clear,No
104,24,Beetroot,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,22:33:36,Beeramguda,0.0,Night,NaN,Clear,No
144,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,04-03-2026,08:07:36,Beeramguda,0.0,Morning,NaN,Clear,No
184,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,14:09:04,Beeramguda,0.0,Afternoon,NaN,Sunny,No
216,16,Organically Grown Tomato (Desi),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,04-03-2026,20:02:21,Beeramguda,0.0,Evening,NaN,Clear,No
222,22,Oraganically Grown Potato,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,04-03-2026,20:03:47,Beeramguda,0.0,Evening,NaN,Clear,No
224,24,Beetroot,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,04-03-2026,20:04:19,Beeramguda,0.0,Evening,NaN,Clear,No
256,16,Organically Grown Tomato (Desi),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:15:25,Beeramguda,NaN,NaN,NaN,NaN,NaN
262,22,Oraganically Grown Potato,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:16:35,Beeramguda,NaN,NaN,NaN,NaN,NaN
264,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-04,23:17:00,Beeramguda,NaN,NaN,NaN,NaN,NaN
304,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-05,07:28:51,Beeramguda,0.0,Morning,NaN,Clear,No
344,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-05,22:00:21,Beeramguda,0.0,Night,NaN,Clear,No
384,24,Beetroot,Other,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,08:56:59,Beeramguda,0.0,Morning,NaN,Clear,No

In [208]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"].isna().sum()

Unnamed: 0                                0
name                                      0
Category                                  0
mrp                                       0
selling_price                             0
offer_percentage                          0
delivery_time                             0
quantity                                  0
scrape_date                               0
scrape_time                               0
location                                  0
Delivery_Charges(Handelling+Delivery)     3
Period                                    3
Surge                                    27
Climate                                   3
Surge_charges                             3
dtype: int64

In [209]:
blinkit_s.loc[(blinkit_s["mrp"]=="Out of Stock")&(blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()),"Delivery_Charges(Handelling+Delivery)"]=0

In [210]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"].isna().sum()

Unnamed: 0                                0
name                                      0
Category                                  0
mrp                                       0
selling_price                             0
offer_percentage                          0
delivery_time                             0
quantity                                  0
scrape_date                               0
scrape_time                               0
location                                  0
Delivery_Charges(Handelling+Delivery)     0
Period                                    3
Surge                                    27
Climate                                   3
Surge_charges                             3
dtype: int64

In [212]:
bigbasket_main=pd.concat([bigbasket_a,bigbasket_su,bigbasket_s],ignore_index=True)

In [213]:
bigbasket_main

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge),Delivery_Charges(Handelling+Delivery+Late_Night_Charges)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,35,fresho! Nagpur Orange,Fruit,129,79,39% OFF,8 MINS,1 kg - (Approx. 6 - 8 pcs),06-03-2026,09:09:26,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
956,36,fresho! Mini Orange Imported,Fruit,144,115.2,20% OFF,8 MINS,500 g,06-03-2026,09:09:36,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
957,37,fresho! Lemon,Vegetable,54,38.5,29% OFF,8 MINS,250 g,06-03-2026,09:09:47,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
958,38,"fresho! Chilli - Green Long, Medium",Vegetable,17,11,35% OFF,8 MINS,100 g,06-03-2026,09:09:57,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
959,39,fresho! Bottle Gourd,Vegetable,34,27.2,20% OFF,8 MINS,1 pc - (300 g - 450 g approx.),06-03-2026,09:10:07,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0

In [214]:
bigbasket_main.duplicated().sum()

np.int64(0)

In [217]:
bigbasket_main[bigbasket_main["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([37., 26., 21., 32., 35.])

In [215]:
bigbasket_main["scrape_date"].unique()

array(['03-03-2026', '04-03-2026', '05-03-2026', '06-03-2026',
       '2026-03-06', '03/03/2026', '2026-03-04', '2026-03-05'],
      dtype=object)

In [216]:
bigbasket_main.to_csv("bigbasket_main.csv",index=False)

In [100]:
bigbasket_s

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery+Late_Night_Charges),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery),Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,114,102,11% OFF,20 MINS,200 g - Pouch,03/03/2026,11:36:02 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:12 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
2,2,Heritage Daily Health Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:21 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03/03/2026,11:36:31 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
4,4,Arokya Full Cream Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:41 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,14 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,14:59:35,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,14 MINS,500 g,2026-03-06,14:59:46,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
317,37,fresho! Lemon,Vegetable,89.0,71.2,20% OFF,14 MINS,500 g,2026-03-06,15:00:01,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,14 MINS,100 g,2026-03-06,15:00:12,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
319,39,fresho! Bottle Gourd,Vegetable,34.0,27.2,20% OFF,14 MINS,1 pc - (300 g - 450 g approx.),2026-03-06,15:00:24,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0

In [218]:
blinkit_main=pd.concat([blinkit_a,blinkit_su,blinkit_s],ignore_index=True)

In [219]:
blinkit_main

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,13 MINS,200 g,2026-03-03,12:56:15,KPHB colony,36.0,Afternoon,NaN,sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,13 MINS,240 g,2026-03-03,12:56:29,KPHB colony,36.0,Afternoon,NaN,sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,13 MINS,500 ml,2026-03-03,12:56:44,KPHB colony,36.0,Afternoon,NaN,sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:56:59,KPHB colony,36.0,Afternoon,NaN,sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:57:15,KPHB colony,36.0,Afternoon,NaN,sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155,35,Nagpur - Orange,Fruit,67.0,59,11% OFF,8 MINS,500 g,2026-03-06,08:59:26,Beeramguda,27.0,Morning,NaN,Clear,No
1156,36,Mini Orange (Imported),Fruit,71.0,57,19% OFF,8 MINS,200 g,2026-03-06,08:59:39,Beeramguda,27.0,Morning,NaN,Clear,No
1157,37,Lemon (Nimakaya),Vegetable,45.0,38,15% OFF,8 MINS,200 g,2026-03-06,08:59:52,Beeramguda,27.0,Morning,NaN,Clear,No
1158,38,Green Chilli (Mirapakaya),Vegetable,13.0,11,15% OFF,8 MINS,100 g,2026-03-06,09:00:06,Beeramguda,27.0,Morning,NaN,Clear,No
1159,39,Bottle Gourd (Sorakaya),Vegetable,31.0,25,19% OFF,8 MINS,400 g,2026-03-06,09:00:20,Beeramguda,27.0,Morning,NaN,Clear,No

In [220]:
blinkit_main.duplicated().sum()

np.int64(1)

In [221]:
blinkit_main[blinkit_main.duplicated()]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
901,20,Premier Mutton Curry Cut,Meat,799,485,39% OFF,13 MINS,480 g,04-03-2026,08:06:35,Beeramguda,27.0,Morning,NaN,Clear,No

In [222]:
bigbasket_main[bigbasket_main["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([37., 26., 21., 32., 35.])

In [121]:
blinkit_main.iloc[900]

Unnamed: 0                                                     20
name                                     Premier Mutton Curry Cut
Category                                                     Meat
mrp                                                           799
selling_price                                                 485
offer_percentage                                          39% OFF
delivery_time                                             13 MINS
quantity                                                    480 g
scrape_date                                            04-03-2026
scrape_time                                              08:06:35
location                                               Beeramguda
Delivery_Charges(Handelling+Delivery)                        27.0
Period                                                    Morning
Surge                                                         NaN
Climate                                                     Clear
Surge_charges                                                  No
Name: 900, dtype: object

In [122]:
blinkit_main.iloc[902]

Unnamed: 0                                                      22
name                                     Oraganically Grown Potato
Category                                                 Vegetable
mrp                                                             40
selling_price                                                   35
offer_percentage                                           12% OFF
delivery_time                                              17 MINS
quantity                                                    250 g
scrape_date                                             04-03-2026
scrape_time                                               08:07:04
location                                                Beeramguda
Delivery_Charges(Handelling+Delivery)                         27.0
Period                                                     Morning
Surge                                                          NaN
Climate                                                      Clear
Surge_charges                                                   No
Name: 902, dtype: object

In [223]:
blinkit_main.to_csv("blinkit_main.csv",index=False)